### ISSUE TITLE
Create repository for pre-mvp singleuser image

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhealth/jupyter-health-software#13]
@maryamv We need a git repo for the singleuser environment for the premvp hub. "singleuser-premvp" would be fine. Please give at least @minrk , @yuvipanda , and @ryanlovett access.

**Comment by minrk** [comment]
Done at: 

- repo: https://github.com/jupyterhealth/singleuser-image
- publishes to: https://quay.io/repository/jupyterhealth/singleuser-premvp
- make default image: https://github.com/2i2c-org/infrastructure/pull/3934
